version: '3.8'

services:  
  nginxserver:
    image: nginx:latest
    container_name: nginxserver
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/mall_infra/nginx/nginx.conf:/etc/nginx/nginx.conf
        #environment:
      #  - ACTIVE_ENV=${ACTIVE_ENV}  # 여기에 환경 변수 설정
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

