version: '3.8'

services:
  mall_product_green:
    image: imhyukjin/mall_product_server:latest
    container_name: mall_product_server_green
    ports:
      - "8081:8081"
    networks:
      - mynetwork   
    environment:
      - PROFILES=green
      - ENV=green

  mall_cart_green:
    image: imhyukjin/mall_cart_server:latest
    container_name: mall_cart_server_green
    ports:
      - "8083:8081"
    networks:
      - mynetwork
    environment:
      - PROFILES=green
      - ENV=green

  mall_order_green:
    image: imhyukjin/mall_order_server:latest
    container_name: mall_order_server_green
    ports:
      - "8085:8081"
    networks:
      - mynetwork
    environment:
      - PROFILES=green
      - ENV=green

networks:
  mynetwork:
    driver: bridge

